#!/usr/bin/env bash

if [ $# -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1

fi

# Disable strict host key checking for scp
export SCP_OPTIONS="-o StrictHostKeyChecking=no"

# Transfer the file to the user's home directory on the server
scp "$SCP_OPTIONS" -i "$4" "$1" "$3@$2":~/
