#!/usr/bin/env bash
# Update the package lists for upgrades and new package installations
apt-get update

# Install nginx
apt-get install -y nginx

# Remove the default nginx configuration
rm /etc/nginx/sites-enabled/default

# Create a new nginx configuration
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html;
    server_name _;
    location / {
        return 200 'Hello World!\n';
        add_header Content-Type text/plain;
    }
}" >/etc/nginx/sites-available/default

# Enable the new configuration
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# Restart nginx
service nginx restart
