#!/usr/bin/env bash
# Configures a new ubuntu machine by installing
# Nginx where it should be listening on port 80
# Serve a page that would return a Hello World string

sudo apt-get update -y && sudo apt-get install nginx -y

# starting nginx service
sudo service nginx start

# allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating new index
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

# Remove existing location block for "/redirect_me"
sudo sed -i '/location \/redirect_me {/,/}/d' /etc/nginx/sites-available/default

# Add new redirect location block at line 24
sudo sed -i '24i\        location /redirect_me {\n            return 301 https://youtu.be/nXLnx8ncZyE;\n        }' /etc/nginx/sites-available/default

# Reload Nginx to apply the changes
sudo service nginx reload
