#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

# Update packages and Install Nginx
echo "Updating packages and installing Nginx..."
sudo apt-get update -y
sudo apt-get install nginx -y

# Start Nginx service
echo "Starting Nginx..."
sudo service nginx start

# Overwrite Nginx default configuration
echo "Configuring Nginx for redirection..."
echo 'server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html;
    server_name _;
    location / {
        try_files $uri $uri/ =404;
    }
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}' | sudo tee /etc/nginx/sites-available/default

# Restart Nginx to apply changes
echo "Restarting Nginx..."
sudo service nginx restart

echo "Nginx configured successfully."
