#!/usr/bin/env bash
# a Bash script that transfers a file from our client to a server:

if [ $# -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1

fi

# file_path="$1"
# server_ip="$2"
# username="$3"
# ssh_key_path="$4"

# Disable strict host key checking for scp
export SCP_OPTIONS="-o StrictHostKeyChecking=no"

# Transfer the file to the user's home directory on the server
scp "$SCP_OPTIONS" -i "$4" "$1" "$3@$2":~/
