#!/usr/bin/env bash
# 1. Install your load balancer

# Update and install HAProxy
echo "Updating packages and installing HAProxy..."
sudo apt update -qq
sudo apt install haproxy -y -qq

# Write the HAProxy configuration
echo "Writing HAProxy configuration..."
server_config=\
"
frontend http_front
	bind *:80
	mode http
	default_backend http_back
backend http_back
	balance roundrobin
  server 513331-web-01 54.165.78.43:80 check
  server 513331-web-02 54.84.65.46:80 check
"

echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

#enable init script
sudo systemctl enable haproxy

#Restart nginx server
sudo service haproxy restart
