#!/usr/bin/env bash
# Updates packages, installs Nginx, modifies the Nginx configuration, and restarts the Nginx service
apt update -y
apt install -y nginx
sed -i 's/8080/80/' /etc/nginx/sites-enabled/default
service nginx restart || service nginx start
