#!/usr/bin/env bash
# advanced task 1

file="/var/run/myscript.pid"

if [ ! -e "$file" ]; then
    touch "$file"
fi
sleep 2 &

echo "$!" > "$file"

trap 'echo I hate the kill command' SIGTERM
trap '[ -e "$file" ] && rm "$file"; exit 0' SIGQUIT SIGTERM
trap 'echo Y U no love me?!' SIGINT

while true; do
    echo "To infinity and beyond"
    sleep 2
done
