#!/bin/bash
# alx school file checker

file_name="school"

# Check if the file exists
if [ -e "$file_name" ]; then
    echo "school file exists."

    # Check if the file is empty
    if [ ! -s "$file_name" ]; then
        echo "school file is empty."
    else
        echo "school file is not empty."
    fi

    # Check if the file is a regular file
    if [ -f "$file_name" ]; then
        echo "school is a regular file."
    fi
else
    echo "school file does not exist."
fi
